package com.metapresence.android.terratraveler.api;

public enum APIName {
	GET_ALL_USERS,
	GET_USER_BY_ID,
	CREATE_USER,
	CREATE_USER_PROFILE,
	GET_USER_PROFILE,
	CREATE_EVENT,
	GET_EVENTS_BY_USER_ID,
	GET_EVENT_BY_ID,
	GET_EVENTS_BY_LOCATION_RADIUS_USING_LOCATION_ID,
	GET_EVENTS_BY_LATITUDE_LONGITUDE_RADIUS,
	CREATE_PLACE
}
